# Discord Bot配置
discord:
  webhooks:
    signal: "https://discord.com/api/webhooks/1343455498187571312/NNHdDTLdTE1Lg5PVKojiMM4CT2_8lNcdnpGlBdIHTTQHAfQ-BeZFAHJtlaNErPZkXBDA"  # 交易信号推送
    upload: "https://discord.com/api/webhooks/1343455502352388179/G_Vkp50OqNErkWgXAMKlKEECBQ5qOj-g3lkArCiofkdnUN9456uANEHEOEoY_qaFJx-4"  # 图片上传接收
    monitor: "https://discord.com/api/webhooks/1343455788697518133/eMO_2hFoerAliK6eBct00rD5U8k-IXGEeD6-Jg0k30_54A7Uchi-IPdbL3LHPYUnPAkA" # 系统监控和其他通知
  upload_channel_id: 1343455502352388179  # 上传频道ID
  username: "SBS Trading Bot"
  embed_color: 0x00ff00
  max_retries: 3
  retry_delay: 5

# 系统配置
system:
  device: "cuda"  # 或 "cpu"
  log_level: "INFO"
  temp_dir: "temp"

# 模型配置
model:
  base_model: "models/llava-sbs"  # 模型路径
  confidence_threshold: 0.8
  batch_size: 1
  prompt_template: |
    你是一个专业的金融图表分析专家，专注于识别和分析SBS(Sequence Based Signal)交易序列。
    你需要分析图表中的：
    1. SBS序列的完整性和有效性
    2. 关键点位的位置和重要性
    3. 交易信号的生成和确认
    4. 市场结构和趋势状态

    请分析这张图表并关注：
    - 突破位置和有效性
    - 回调的深度和形态
    - 双顶/双底的形成
    - 流动性获取区域
    - SCE信号确认
    - SMA20和SMA200趋势辅助

    分析要求：

    对于SBS序列，请确认：
    1. 突破的清晰度和有效性
    2. 回调的规范性（0.382-0.618）
    3. 确认阶段的完整性
    4. 整体序列的时间结构

    请标识以下关键点位：
    1. 突破点
    2. Point 1 (回调高点)
    3. Point 2 (回调低点)
    4. Point 3 (确认高点)
    5. Point 4 (确认低点)

    请提供：
    1. 信号类型（做多/做空）
    2. 入场区域建议
    3. 止损位置
    4. 目标位置

    请按以下格式输出分析结果：

    序列评估：
    - 有效性：[是/否]
    - 完整度：[0-100%]
    - 可信度：[0-100%]

    关键点位：
    - 突破点：[价格水平]
    - Point 1：[价格水平]
    - Point 2：[价格水平]
    - Point 3：[价格水平]
    - Point 4：[价格水平]

    交易信号：
    - 方向：[多/空]
    - 入场区域：[价格范围]
    - 止损位：[价格水平]
    - 目标位：[价格水平]

    趋势辅助分析：
    - SMA20趋势：[上升/下降/盘整]
    - SMA200趋势：[上升/下降/盘整]
    - 整体趋势评估：[描述]

    风险评估：
    - 风险等级：[低/中/高]
    - 主要风险点：[描述]

    注意事项：
    1. 只在确认看到清晰的SBS序列时才生成信号
    2. 对于不完整或不确定的形态，请明确指出原因
    3. 如果发现任何潜在风险，请在风险评估中详细说明
    4. 所有价格水平必须精确到小数点后4位
    5. 确保所有关键点位的时间顺序正确

# 通知配置
notification:
  enabled: true
  cooldown: 300  # 通知冷却时间（秒）
  max_daily: 100 # 每日最大通知次数 